namespace QL_KhachSan
{
    partial class F_DoUong
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(F_DoUong));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.dtgfmenu = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtNameF = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbCateF = new System.Windows.Forms.ComboBox();
            this.btnAddF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btndelF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnreset = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btneditF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCostF = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.dtgfmenu)).BeginInit();
            this.SuspendLayout();
            // 
            // dtgfmenu
            // 
            this.dtgfmenu.AllowCustomTheming = false;
            this.dtgfmenu.AllowUserToAddRows = false;
            this.dtgfmenu.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtgfmenu.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgfmenu.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtgfmenu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgfmenu.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgfmenu.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgfmenu.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgfmenu.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgfmenu.ColumnHeadersHeight = 40;
            this.dtgfmenu.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgfmenu.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgfmenu.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgfmenu.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgfmenu.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgfmenu.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgfmenu.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgfmenu.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtgfmenu.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgfmenu.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgfmenu.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtgfmenu.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtgfmenu.CurrentTheme.Name = null;
            this.dtgfmenu.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgfmenu.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgfmenu.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgfmenu.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgfmenu.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgfmenu.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgfmenu.EnableHeadersVisualStyles = false;
            this.dtgfmenu.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgfmenu.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtgfmenu.HeaderBgColor = System.Drawing.Color.Black;
            this.dtgfmenu.HeaderForeColor = System.Drawing.Color.White;
            this.dtgfmenu.Location = new System.Drawing.Point(322, 12);
            this.dtgfmenu.Name = "dtgfmenu";
            this.dtgfmenu.ReadOnly = true;
            this.dtgfmenu.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            this.dtgfmenu.RowHeadersVisible = false;
            this.dtgfmenu.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToAllHeaders;
            this.dtgfmenu.RowTemplate.Height = 40;
            this.dtgfmenu.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgfmenu.Size = new System.Drawing.Size(266, 342);
            this.dtgfmenu.TabIndex = 0;
            this.dtgfmenu.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtgfmenu.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtgfmenu_CellContentClick);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel1.Location = new System.Drawing.Point(22, 69);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(28, 21);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Tên:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtNameF
            // 
            this.txtNameF.AcceptsReturn = false;
            this.txtNameF.AcceptsTab = false;
            this.txtNameF.AnimationSpeed = 200;
            this.txtNameF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNameF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNameF.AutoSizeHeight = true;
            this.txtNameF.BackColor = System.Drawing.Color.Transparent;
            this.txtNameF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNameF.BackgroundImage")));
            this.txtNameF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNameF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNameF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNameF.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNameF.BorderRadius = 1;
            this.txtNameF.BorderThickness = 1;
            this.txtNameF.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNameF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNameF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameF.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNameF.DefaultText = "";
            this.txtNameF.FillColor = System.Drawing.Color.White;
            this.txtNameF.ForeColor = System.Drawing.Color.Black;
            this.txtNameF.HideSelection = true;
            this.txtNameF.IconLeft = null;
            this.txtNameF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameF.IconPadding = 10;
            this.txtNameF.IconRight = null;
            this.txtNameF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNameF.Lines = new string[0];
            this.txtNameF.Location = new System.Drawing.Point(61, 69);
            this.txtNameF.MaxLength = 32767;
            this.txtNameF.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNameF.Modified = false;
            this.txtNameF.Multiline = false;
            this.txtNameF.Name = "txtNameF";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameF.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNameF.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameF.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNameF.OnIdleState = stateProperties4;
            this.txtNameF.Padding = new System.Windows.Forms.Padding(3);
            this.txtNameF.PasswordChar = '\0';
            this.txtNameF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNameF.PlaceholderText = "Tên món";
            this.txtNameF.ReadOnly = false;
            this.txtNameF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNameF.SelectedText = "";
            this.txtNameF.SelectionLength = 0;
            this.txtNameF.SelectionStart = 0;
            this.txtNameF.ShortcutsEnabled = true;
            this.txtNameF.Size = new System.Drawing.Size(221, 30);
            this.txtNameF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNameF.TabIndex = 2;
            this.txtNameF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNameF.TextMarginBottom = 0;
            this.txtNameF.TextMarginLeft = 3;
            this.txtNameF.TextMarginTop = 1;
            this.txtNameF.TextPlaceholder = "Tên món";
            this.txtNameF.UseSystemPasswordChar = false;
            this.txtNameF.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel2.Location = new System.Drawing.Point(22, 154);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(26, 21);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Giá:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel3.Location = new System.Drawing.Point(22, 117);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(33, 21);
            this.bunifuLabel3.TabIndex = 5;
            this.bunifuLabel3.Text = "Mục:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbCateF
            // 
            this.cbCateF.FormattingEnabled = true;
            this.cbCateF.Items.AddRange(new object[] {
            "Food",
            "Drink"});
            this.cbCateF.Location = new System.Drawing.Point(61, 116);
            this.cbCateF.Name = "cbCateF";
            this.cbCateF.Size = new System.Drawing.Size(221, 21);
            this.cbCateF.TabIndex = 6;
            // 
            // btnAddF
            // 
            this.btnAddF.AllowAnimations = true;
            this.btnAddF.AllowMouseEffects = true;
            this.btnAddF.AllowToggling = false;
            this.btnAddF.AnimationSpeed = 200;
            this.btnAddF.AutoGenerateColors = false;
            this.btnAddF.AutoRoundBorders = true;
            this.btnAddF.AutoSizeLeftIcon = true;
            this.btnAddF.AutoSizeRightIcon = true;
            this.btnAddF.BackColor = System.Drawing.Color.Transparent;
            this.btnAddF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAddF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddF.BackgroundImage")));
            this.btnAddF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddF.ButtonText = "Add";
            this.btnAddF.ButtonTextMarginLeft = 0;
            this.btnAddF.ColorContrastOnClick = 45;
            this.btnAddF.ColorContrastOnHover = 45;
            this.btnAddF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAddF.CustomizableEdges = borderEdges1;
            this.btnAddF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddF.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAddF.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAddF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddF.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAddF.ForeColor = System.Drawing.Color.White;
            this.btnAddF.IconLeft = null;
            this.btnAddF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddF.IconMarginLeft = 11;
            this.btnAddF.IconPadding = 10;
            this.btnAddF.IconRight = null;
            this.btnAddF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddF.IconSize = 25;
            this.btnAddF.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAddF.IdleBorderRadius = 0;
            this.btnAddF.IdleBorderThickness = 0;
            this.btnAddF.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAddF.IdleIconLeftImage = null;
            this.btnAddF.IdleIconRightImage = null;
            this.btnAddF.IndicateFocus = false;
            this.btnAddF.Location = new System.Drawing.Point(61, 208);
            this.btnAddF.Name = "btnAddF";
            this.btnAddF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddF.OnDisabledState.BorderRadius = 39;
            this.btnAddF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddF.OnDisabledState.BorderThickness = 1;
            this.btnAddF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddF.OnDisabledState.IconLeftImage = null;
            this.btnAddF.OnDisabledState.IconRightImage = null;
            this.btnAddF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAddF.onHoverState.BorderRadius = 39;
            this.btnAddF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddF.onHoverState.BorderThickness = 1;
            this.btnAddF.onHoverState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btnAddF.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAddF.onHoverState.IconLeftImage = null;
            this.btnAddF.onHoverState.IconRightImage = null;
            this.btnAddF.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAddF.OnIdleState.BorderRadius = 39;
            this.btnAddF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddF.OnIdleState.BorderThickness = 1;
            this.btnAddF.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.btnAddF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddF.OnIdleState.IconLeftImage = null;
            this.btnAddF.OnIdleState.IconRightImage = null;
            this.btnAddF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAddF.OnPressedState.BorderRadius = 39;
            this.btnAddF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddF.OnPressedState.BorderThickness = 1;
            this.btnAddF.OnPressedState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btnAddF.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnAddF.OnPressedState.IconLeftImage = null;
            this.btnAddF.OnPressedState.IconRightImage = null;
            this.btnAddF.Size = new System.Drawing.Size(81, 39);
            this.btnAddF.TabIndex = 7;
            this.btnAddF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddF.TextMarginLeft = 0;
            this.btnAddF.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddF.UseDefaultRadiusAndThickness = true;
            this.btnAddF.Click += new System.EventHandler(this.btnAddF_Click);
            // 
            // btndelF
            // 
            this.btndelF.AllowAnimations = true;
            this.btndelF.AllowMouseEffects = true;
            this.btndelF.AllowToggling = false;
            this.btndelF.AnimationSpeed = 200;
            this.btndelF.AutoGenerateColors = false;
            this.btndelF.AutoRoundBorders = true;
            this.btndelF.AutoSizeLeftIcon = true;
            this.btndelF.AutoSizeRightIcon = true;
            this.btndelF.BackColor = System.Drawing.Color.Transparent;
            this.btndelF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btndelF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btndelF.BackgroundImage")));
            this.btndelF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndelF.ButtonText = "Delete";
            this.btndelF.ButtonTextMarginLeft = 0;
            this.btndelF.ColorContrastOnClick = 45;
            this.btndelF.ColorContrastOnHover = 45;
            this.btndelF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btndelF.CustomizableEdges = borderEdges2;
            this.btndelF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btndelF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btndelF.DisabledFillColor = System.Drawing.Color.Empty;
            this.btndelF.DisabledForecolor = System.Drawing.Color.Empty;
            this.btndelF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btndelF.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btndelF.ForeColor = System.Drawing.Color.White;
            this.btndelF.IconLeft = null;
            this.btndelF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btndelF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btndelF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btndelF.IconMarginLeft = 11;
            this.btndelF.IconPadding = 10;
            this.btndelF.IconRight = null;
            this.btndelF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btndelF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btndelF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btndelF.IconSize = 25;
            this.btndelF.IdleBorderColor = System.Drawing.Color.Empty;
            this.btndelF.IdleBorderRadius = 0;
            this.btndelF.IdleBorderThickness = 0;
            this.btndelF.IdleFillColor = System.Drawing.Color.Empty;
            this.btndelF.IdleIconLeftImage = null;
            this.btndelF.IdleIconRightImage = null;
            this.btndelF.IndicateFocus = false;
            this.btndelF.Location = new System.Drawing.Point(61, 262);
            this.btndelF.Name = "btndelF";
            this.btndelF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btndelF.OnDisabledState.BorderRadius = 39;
            this.btndelF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndelF.OnDisabledState.BorderThickness = 1;
            this.btndelF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btndelF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btndelF.OnDisabledState.IconLeftImage = null;
            this.btndelF.OnDisabledState.IconRightImage = null;
            this.btndelF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btndelF.onHoverState.BorderRadius = 39;
            this.btndelF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndelF.onHoverState.BorderThickness = 1;
            this.btndelF.onHoverState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btndelF.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btndelF.onHoverState.IconLeftImage = null;
            this.btndelF.onHoverState.IconRightImage = null;
            this.btndelF.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btndelF.OnIdleState.BorderRadius = 39;
            this.btndelF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndelF.OnIdleState.BorderThickness = 1;
            this.btndelF.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.btndelF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btndelF.OnIdleState.IconLeftImage = null;
            this.btndelF.OnIdleState.IconRightImage = null;
            this.btndelF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btndelF.OnPressedState.BorderRadius = 39;
            this.btndelF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndelF.OnPressedState.BorderThickness = 1;
            this.btndelF.OnPressedState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btndelF.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btndelF.OnPressedState.IconLeftImage = null;
            this.btndelF.OnPressedState.IconRightImage = null;
            this.btndelF.Size = new System.Drawing.Size(81, 39);
            this.btndelF.TabIndex = 8;
            this.btndelF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btndelF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btndelF.TextMarginLeft = 0;
            this.btndelF.TextPadding = new System.Windows.Forms.Padding(0);
            this.btndelF.UseDefaultRadiusAndThickness = true;
            this.btndelF.Click += new System.EventHandler(this.btndelF_Click);
            // 
            // btnreset
            // 
            this.btnreset.AllowAnimations = true;
            this.btnreset.AllowMouseEffects = true;
            this.btnreset.AllowToggling = false;
            this.btnreset.AnimationSpeed = 200;
            this.btnreset.AutoGenerateColors = false;
            this.btnreset.AutoRoundBorders = true;
            this.btnreset.AutoSizeLeftIcon = true;
            this.btnreset.AutoSizeRightIcon = true;
            this.btnreset.BackColor = System.Drawing.Color.Transparent;
            this.btnreset.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnreset.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnreset.BackgroundImage")));
            this.btnreset.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.ButtonText = "Reset";
            this.btnreset.ButtonTextMarginLeft = 0;
            this.btnreset.ColorContrastOnClick = 45;
            this.btnreset.ColorContrastOnHover = 45;
            this.btnreset.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnreset.CustomizableEdges = borderEdges3;
            this.btnreset.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnreset.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreset.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnreset.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnreset.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnreset.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnreset.ForeColor = System.Drawing.Color.White;
            this.btnreset.IconLeft = null;
            this.btnreset.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnreset.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnreset.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnreset.IconMarginLeft = 11;
            this.btnreset.IconPadding = 10;
            this.btnreset.IconRight = null;
            this.btnreset.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnreset.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnreset.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnreset.IconSize = 25;
            this.btnreset.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnreset.IdleBorderRadius = 0;
            this.btnreset.IdleBorderThickness = 0;
            this.btnreset.IdleFillColor = System.Drawing.Color.Empty;
            this.btnreset.IdleIconLeftImage = null;
            this.btnreset.IdleIconRightImage = null;
            this.btnreset.IndicateFocus = false;
            this.btnreset.Location = new System.Drawing.Point(201, 262);
            this.btnreset.Name = "btnreset";
            this.btnreset.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreset.OnDisabledState.BorderRadius = 39;
            this.btnreset.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnDisabledState.BorderThickness = 1;
            this.btnreset.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnreset.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnreset.OnDisabledState.IconLeftImage = null;
            this.btnreset.OnDisabledState.IconRightImage = null;
            this.btnreset.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnreset.onHoverState.BorderRadius = 39;
            this.btnreset.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.onHoverState.BorderThickness = 1;
            this.btnreset.onHoverState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btnreset.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnreset.onHoverState.IconLeftImage = null;
            this.btnreset.onHoverState.IconRightImage = null;
            this.btnreset.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnreset.OnIdleState.BorderRadius = 39;
            this.btnreset.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnIdleState.BorderThickness = 1;
            this.btnreset.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.btnreset.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnreset.OnIdleState.IconLeftImage = null;
            this.btnreset.OnIdleState.IconRightImage = null;
            this.btnreset.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnreset.OnPressedState.BorderRadius = 39;
            this.btnreset.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnreset.OnPressedState.BorderThickness = 1;
            this.btnreset.OnPressedState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btnreset.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnreset.OnPressedState.IconLeftImage = null;
            this.btnreset.OnPressedState.IconRightImage = null;
            this.btnreset.Size = new System.Drawing.Size(81, 39);
            this.btnreset.TabIndex = 10;
            this.btnreset.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnreset.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnreset.TextMarginLeft = 0;
            this.btnreset.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnreset.UseDefaultRadiusAndThickness = true;
            // 
            // btneditF
            // 
            this.btneditF.AllowAnimations = true;
            this.btneditF.AllowMouseEffects = true;
            this.btneditF.AllowToggling = false;
            this.btneditF.AnimationSpeed = 200;
            this.btneditF.AutoGenerateColors = false;
            this.btneditF.AutoRoundBorders = true;
            this.btneditF.AutoSizeLeftIcon = true;
            this.btneditF.AutoSizeRightIcon = true;
            this.btneditF.BackColor = System.Drawing.Color.Transparent;
            this.btneditF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btneditF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btneditF.BackgroundImage")));
            this.btneditF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneditF.ButtonText = "Edit";
            this.btneditF.ButtonTextMarginLeft = 0;
            this.btneditF.ColorContrastOnClick = 45;
            this.btneditF.ColorContrastOnHover = 45;
            this.btneditF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btneditF.CustomizableEdges = borderEdges4;
            this.btneditF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btneditF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneditF.DisabledFillColor = System.Drawing.Color.Empty;
            this.btneditF.DisabledForecolor = System.Drawing.Color.Empty;
            this.btneditF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btneditF.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btneditF.ForeColor = System.Drawing.Color.White;
            this.btneditF.IconLeft = null;
            this.btneditF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btneditF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btneditF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btneditF.IconMarginLeft = 11;
            this.btneditF.IconPadding = 10;
            this.btneditF.IconRight = null;
            this.btneditF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btneditF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btneditF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btneditF.IconSize = 25;
            this.btneditF.IdleBorderColor = System.Drawing.Color.Empty;
            this.btneditF.IdleBorderRadius = 0;
            this.btneditF.IdleBorderThickness = 0;
            this.btneditF.IdleFillColor = System.Drawing.Color.Empty;
            this.btneditF.IdleIconLeftImage = null;
            this.btneditF.IdleIconRightImage = null;
            this.btneditF.IndicateFocus = false;
            this.btneditF.Location = new System.Drawing.Point(201, 208);
            this.btneditF.Name = "btneditF";
            this.btneditF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneditF.OnDisabledState.BorderRadius = 39;
            this.btneditF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneditF.OnDisabledState.BorderThickness = 1;
            this.btneditF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneditF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneditF.OnDisabledState.IconLeftImage = null;
            this.btneditF.OnDisabledState.IconRightImage = null;
            this.btneditF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btneditF.onHoverState.BorderRadius = 39;
            this.btneditF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneditF.onHoverState.BorderThickness = 1;
            this.btneditF.onHoverState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btneditF.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btneditF.onHoverState.IconLeftImage = null;
            this.btneditF.onHoverState.IconRightImage = null;
            this.btneditF.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btneditF.OnIdleState.BorderRadius = 39;
            this.btneditF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneditF.OnIdleState.BorderThickness = 1;
            this.btneditF.OnIdleState.FillColor = System.Drawing.Color.Goldenrod;
            this.btneditF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btneditF.OnIdleState.IconLeftImage = null;
            this.btneditF.OnIdleState.IconRightImage = null;
            this.btneditF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneditF.OnPressedState.BorderRadius = 39;
            this.btneditF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneditF.OnPressedState.BorderThickness = 1;
            this.btneditF.OnPressedState.FillColor = System.Drawing.Color.LemonChiffon;
            this.btneditF.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btneditF.OnPressedState.IconLeftImage = null;
            this.btneditF.OnPressedState.IconRightImage = null;
            this.btneditF.Size = new System.Drawing.Size(81, 39);
            this.btneditF.TabIndex = 9;
            this.btneditF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btneditF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btneditF.TextMarginLeft = 0;
            this.btneditF.TextPadding = new System.Windows.Forms.Padding(0);
            this.btneditF.UseDefaultRadiusAndThickness = true;
            this.btneditF.Click += new System.EventHandler(this.btneditF_Click);
            // 
            // txtCostF
            // 
            this.txtCostF.AcceptsReturn = false;
            this.txtCostF.AcceptsTab = false;
            this.txtCostF.AnimationSpeed = 200;
            this.txtCostF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCostF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCostF.AutoSizeHeight = true;
            this.txtCostF.BackColor = System.Drawing.Color.Transparent;
            this.txtCostF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCostF.BackgroundImage")));
            this.txtCostF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCostF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCostF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCostF.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCostF.BorderRadius = 1;
            this.txtCostF.BorderThickness = 1;
            this.txtCostF.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCostF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCostF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCostF.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCostF.DefaultText = "";
            this.txtCostF.FillColor = System.Drawing.Color.White;
            this.txtCostF.ForeColor = System.Drawing.Color.Black;
            this.txtCostF.HideSelection = true;
            this.txtCostF.IconLeft = null;
            this.txtCostF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCostF.IconPadding = 10;
            this.txtCostF.IconRight = null;
            this.txtCostF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCostF.Lines = new string[0];
            this.txtCostF.Location = new System.Drawing.Point(61, 154);
            this.txtCostF.MaxLength = 32767;
            this.txtCostF.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCostF.Modified = false;
            this.txtCostF.Multiline = false;
            this.txtCostF.Name = "txtCostF";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCostF.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCostF.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCostF.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCostF.OnIdleState = stateProperties8;
            this.txtCostF.Padding = new System.Windows.Forms.Padding(3);
            this.txtCostF.PasswordChar = '\0';
            this.txtCostF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCostF.PlaceholderText = "Giá";
            this.txtCostF.ReadOnly = false;
            this.txtCostF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCostF.SelectedText = "";
            this.txtCostF.SelectionLength = 0;
            this.txtCostF.SelectionStart = 0;
            this.txtCostF.ShortcutsEnabled = true;
            this.txtCostF.Size = new System.Drawing.Size(221, 30);
            this.txtCostF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCostF.TabIndex = 4;
            this.txtCostF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCostF.TextMarginBottom = 0;
            this.txtCostF.TextMarginLeft = 3;
            this.txtCostF.TextMarginTop = 1;
            this.txtCostF.TextPlaceholder = "Giá";
            this.txtCostF.UseSystemPasswordChar = false;
            this.txtCostF.WordWrap = true;
            // 
            // txtID
            // 
            this.txtID.AcceptsReturn = false;
            this.txtID.AcceptsTab = false;
            this.txtID.AnimationSpeed = 200;
            this.txtID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtID.AutoSizeHeight = true;
            this.txtID.BackColor = System.Drawing.Color.Transparent;
            this.txtID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtID.BackgroundImage")));
            this.txtID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtID.BorderRadius = 1;
            this.txtID.BorderThickness = 1;
            this.txtID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtID.DefaultText = "";
            this.txtID.FillColor = System.Drawing.Color.White;
            this.txtID.ForeColor = System.Drawing.Color.Black;
            this.txtID.HideSelection = true;
            this.txtID.IconLeft = null;
            this.txtID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtID.IconPadding = 10;
            this.txtID.IconRight = null;
            this.txtID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtID.Lines = new string[0];
            this.txtID.Location = new System.Drawing.Point(61, 12);
            this.txtID.MaxLength = 32767;
            this.txtID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtID.Modified = false;
            this.txtID.Multiline = false;
            this.txtID.Name = "txtID";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtID.OnIdleState = stateProperties12;
            this.txtID.Padding = new System.Windows.Forms.Padding(3);
            this.txtID.PasswordChar = '\0';
            this.txtID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtID.PlaceholderText = "ID";
            this.txtID.ReadOnly = true;
            this.txtID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtID.SelectedText = "";
            this.txtID.SelectionLength = 0;
            this.txtID.SelectionStart = 0;
            this.txtID.ShortcutsEnabled = true;
            this.txtID.Size = new System.Drawing.Size(221, 30);
            this.txtID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtID.TabIndex = 12;
            this.txtID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtID.TextMarginBottom = 0;
            this.txtID.TextMarginLeft = 3;
            this.txtID.TextMarginTop = 1;
            this.txtID.TextPlaceholder = "ID";
            this.txtID.UseSystemPasswordChar = false;
            this.txtID.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel4.Location = new System.Drawing.Point(22, 12);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(15, 21);
            this.bunifuLabel4.TabIndex = 11;
            this.bunifuLabel4.Text = "ID";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // F_DoUong
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(807, 586);
            this.ControlBox = false;
            this.Controls.Add(this.txtID);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.btnreset);
            this.Controls.Add(this.btneditF);
            this.Controls.Add(this.btndelF);
            this.Controls.Add(this.btnAddF);
            this.Controls.Add(this.cbCateF);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.txtCostF);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txtNameF);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.dtgfmenu);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "F_DoUong";
            this.Text = "F_DoUong";
            ((System.ComponentModel.ISupportInitialize)(this.dtgfmenu)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dtgfmenu;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtNameF;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.ComboBox cbCateF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btndelF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnreset;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btneditF;
        private Bunifu.UI.WinForms.BunifuTextBox txtCostF;
        private Bunifu.UI.WinForms.BunifuTextBox txtID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
    }
}