namespace QL_KhachSan
{
    partial class F_NhanVienCRUD
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(F_NhanVienCRUD));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.pb_image = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bDP_NgaySinh = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txt_GioiTinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_ChucVu = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Ho = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_Luong1h = new Bunifu.UI.WinForms.BunifuLabel();
            this.txt_Ten = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Luong1h = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Sdt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_MaSoThue = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_CCCD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_Luong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbl_Ho = new System.Windows.Forms.Label();
            this.lbl_Ten = new System.Windows.Forms.Label();
            this.lbl_GioiTinh = new System.Windows.Forms.Label();
            this.lbl_NgaySinh = new System.Windows.Forms.Label();
            this.lbl_ChucVu = new System.Windows.Forms.Label();
            this.lbl_Sdt = new System.Windows.Forms.Label();
            this.lbl_CCCD = new System.Windows.Forms.Label();
            this.lbl_MaSoThue = new System.Windows.Forms.Label();
            this.lbl_Email = new System.Windows.Forms.Label();
            this.lbl_Luong = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pb_image)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // pb_image
            // 
            this.pb_image.AllowFocused = false;
            this.pb_image.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pb_image.AutoSizeHeight = true;
            this.pb_image.BorderRadius = 135;
            this.pb_image.Image = ((System.Drawing.Image)(resources.GetObject("pb_image.Image")));
            this.pb_image.IsCircle = true;
            this.pb_image.Location = new System.Drawing.Point(46, 213);
            this.pb_image.Name = "pb_image";
            this.pb_image.Size = new System.Drawing.Size(270, 270);
            this.pb_image.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pb_image.TabIndex = 0;
            this.pb_image.TabStop = false;
            this.pb_image.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.pb_image.Click += new System.EventHandler(this.pb_image_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.bDP_NgaySinh);
            this.panel1.Location = new System.Drawing.Point(562, 239);
            this.panel1.Margin = new System.Windows.Forms.Padding(0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(221, 37);
            this.panel1.TabIndex = 47;
            // 
            // bDP_NgaySinh
            // 
            this.bDP_NgaySinh.BackColor = System.Drawing.Color.White;
            this.bDP_NgaySinh.BorderColor = System.Drawing.Color.White;
            this.bDP_NgaySinh.BorderRadius = 0;
            this.bDP_NgaySinh.CalendarForeColor = System.Drawing.Color.White;
            this.bDP_NgaySinh.CalendarMonthBackground = System.Drawing.Color.WhiteSmoke;
            this.bDP_NgaySinh.CalendarTitleForeColor = System.Drawing.Color.White;
            this.bDP_NgaySinh.CalendarTrailingForeColor = System.Drawing.Color.White;
            this.bDP_NgaySinh.Color = System.Drawing.Color.White;
            this.bDP_NgaySinh.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bDP_NgaySinh.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bDP_NgaySinh.DisabledColor = System.Drawing.Color.Black;
            this.bDP_NgaySinh.DisplayWeekNumbers = false;
            this.bDP_NgaySinh.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bDP_NgaySinh.DPHeight = 0;
            this.bDP_NgaySinh.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bDP_NgaySinh.FillDatePicker = false;
            this.bDP_NgaySinh.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bDP_NgaySinh.ForeColor = System.Drawing.Color.Black;
            this.bDP_NgaySinh.Icon = ((System.Drawing.Image)(resources.GetObject("bDP_NgaySinh.Icon")));
            this.bDP_NgaySinh.IconColor = System.Drawing.Color.Black;
            this.bDP_NgaySinh.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bDP_NgaySinh.LeftTextMargin = 5;
            this.bDP_NgaySinh.Location = new System.Drawing.Point(0, 0);
            this.bDP_NgaySinh.Margin = new System.Windows.Forms.Padding(0);
            this.bDP_NgaySinh.MinimumSize = new System.Drawing.Size(4, 32);
            this.bDP_NgaySinh.Name = "bDP_NgaySinh";
            this.bDP_NgaySinh.Size = new System.Drawing.Size(221, 32);
            this.bDP_NgaySinh.TabIndex = 5;
            this.bDP_NgaySinh.Value = new System.DateTime(2024, 4, 2, 9, 32, 0, 0);
            // 
            // txt_GioiTinh
            // 
            this.txt_GioiTinh.AcceptsReturn = false;
            this.txt_GioiTinh.AcceptsTab = false;
            this.txt_GioiTinh.AnimationSpeed = 200;
            this.txt_GioiTinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_GioiTinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_GioiTinh.AutoSizeHeight = true;
            this.txt_GioiTinh.BackColor = System.Drawing.Color.Transparent;
            this.txt_GioiTinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_GioiTinh.BackgroundImage")));
            this.txt_GioiTinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_GioiTinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_GioiTinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_GioiTinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_GioiTinh.BorderRadius = 1;
            this.txt_GioiTinh.BorderThickness = 1;
            this.txt_GioiTinh.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_GioiTinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_GioiTinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_GioiTinh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_GioiTinh.DefaultText = "";
            this.txt_GioiTinh.FillColor = System.Drawing.Color.White;
            this.txt_GioiTinh.ForeColor = System.Drawing.Color.Black;
            this.txt_GioiTinh.HideSelection = true;
            this.txt_GioiTinh.IconLeft = null;
            this.txt_GioiTinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_GioiTinh.IconPadding = 10;
            this.txt_GioiTinh.IconRight = null;
            this.txt_GioiTinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_GioiTinh.Lines = new string[0];
            this.txt_GioiTinh.Location = new System.Drawing.Point(398, 235);
            this.txt_GioiTinh.Margin = new System.Windows.Forms.Padding(0);
            this.txt_GioiTinh.MaxLength = 32767;
            this.txt_GioiTinh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_GioiTinh.Modified = false;
            this.txt_GioiTinh.Multiline = false;
            this.txt_GioiTinh.Name = "txt_GioiTinh";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_GioiTinh.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Black;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_GioiTinh.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_GioiTinh.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_GioiTinh.OnIdleState = stateProperties4;
            this.txt_GioiTinh.Padding = new System.Windows.Forms.Padding(3);
            this.txt_GioiTinh.PasswordChar = '\0';
            this.txt_GioiTinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_GioiTinh.PlaceholderText = "Enter text";
            this.txt_GioiTinh.ReadOnly = false;
            this.txt_GioiTinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_GioiTinh.SelectedText = "";
            this.txt_GioiTinh.SelectionLength = 0;
            this.txt_GioiTinh.SelectionStart = 0;
            this.txt_GioiTinh.ShortcutsEnabled = true;
            this.txt_GioiTinh.Size = new System.Drawing.Size(149, 43);
            this.txt_GioiTinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_GioiTinh.TabIndex = 46;
            this.txt_GioiTinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_GioiTinh.TextMarginBottom = 0;
            this.txt_GioiTinh.TextMarginLeft = 3;
            this.txt_GioiTinh.TextMarginTop = 1;
            this.txt_GioiTinh.TextPlaceholder = "Enter text";
            this.txt_GioiTinh.UseSystemPasswordChar = false;
            this.txt_GioiTinh.WordWrap = true;
            // 
            // txt_ChucVu
            // 
            this.txt_ChucVu.AcceptsReturn = false;
            this.txt_ChucVu.AcceptsTab = false;
            this.txt_ChucVu.AnimationSpeed = 200;
            this.txt_ChucVu.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_ChucVu.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_ChucVu.AutoSizeHeight = true;
            this.txt_ChucVu.BackColor = System.Drawing.Color.Transparent;
            this.txt_ChucVu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_ChucVu.BackgroundImage")));
            this.txt_ChucVu.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_ChucVu.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_ChucVu.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_ChucVu.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_ChucVu.BorderRadius = 1;
            this.txt_ChucVu.BorderThickness = 1;
            this.txt_ChucVu.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_ChucVu.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_ChucVu.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ChucVu.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_ChucVu.DefaultText = "";
            this.txt_ChucVu.FillColor = System.Drawing.Color.White;
            this.txt_ChucVu.ForeColor = System.Drawing.Color.Black;
            this.txt_ChucVu.HideSelection = true;
            this.txt_ChucVu.IconLeft = null;
            this.txt_ChucVu.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ChucVu.IconPadding = 10;
            this.txt_ChucVu.IconRight = null;
            this.txt_ChucVu.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_ChucVu.Lines = new string[0];
            this.txt_ChucVu.Location = new System.Drawing.Point(398, 322);
            this.txt_ChucVu.Margin = new System.Windows.Forms.Padding(0);
            this.txt_ChucVu.MaxLength = 32767;
            this.txt_ChucVu.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_ChucVu.Modified = false;
            this.txt_ChucVu.Multiline = false;
            this.txt_ChucVu.Name = "txt_ChucVu";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ChucVu.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Black;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_ChucVu.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ChucVu.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_ChucVu.OnIdleState = stateProperties8;
            this.txt_ChucVu.Padding = new System.Windows.Forms.Padding(3);
            this.txt_ChucVu.PasswordChar = '\0';
            this.txt_ChucVu.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_ChucVu.PlaceholderText = "Enter text";
            this.txt_ChucVu.ReadOnly = false;
            this.txt_ChucVu.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_ChucVu.SelectedText = "";
            this.txt_ChucVu.SelectionLength = 0;
            this.txt_ChucVu.SelectionStart = 0;
            this.txt_ChucVu.ShortcutsEnabled = true;
            this.txt_ChucVu.Size = new System.Drawing.Size(149, 43);
            this.txt_ChucVu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_ChucVu.TabIndex = 43;
            this.txt_ChucVu.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_ChucVu.TextMarginBottom = 0;
            this.txt_ChucVu.TextMarginLeft = 3;
            this.txt_ChucVu.TextMarginTop = 1;
            this.txt_ChucVu.TextPlaceholder = "Enter text";
            this.txt_ChucVu.UseSystemPasswordChar = false;
            this.txt_ChucVu.WordWrap = true;
            // 
            // txt_Ho
            // 
            this.txt_Ho.AcceptsReturn = false;
            this.txt_Ho.AcceptsTab = false;
            this.txt_Ho.AnimationSpeed = 200;
            this.txt_Ho.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Ho.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Ho.AutoSizeHeight = true;
            this.txt_Ho.BackColor = System.Drawing.Color.Transparent;
            this.txt_Ho.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Ho.BackgroundImage")));
            this.txt_Ho.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Ho.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Ho.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Ho.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Ho.BorderRadius = 1;
            this.txt_Ho.BorderThickness = 1;
            this.txt_Ho.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Ho.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Ho.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ho.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Ho.DefaultText = "";
            this.txt_Ho.FillColor = System.Drawing.Color.White;
            this.txt_Ho.ForeColor = System.Drawing.Color.Black;
            this.txt_Ho.HideSelection = true;
            this.txt_Ho.IconLeft = null;
            this.txt_Ho.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ho.IconPadding = 10;
            this.txt_Ho.IconRight = null;
            this.txt_Ho.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ho.Lines = new string[0];
            this.txt_Ho.Location = new System.Drawing.Point(398, 158);
            this.txt_Ho.Margin = new System.Windows.Forms.Padding(0);
            this.txt_Ho.MaxLength = 32767;
            this.txt_Ho.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Ho.Modified = false;
            this.txt_Ho.Multiline = false;
            this.txt_Ho.Name = "txt_Ho";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ho.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Black;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Ho.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ho.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ho.OnIdleState = stateProperties12;
            this.txt_Ho.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Ho.PasswordChar = '\0';
            this.txt_Ho.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Ho.PlaceholderText = "Enter text";
            this.txt_Ho.ReadOnly = false;
            this.txt_Ho.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Ho.SelectedText = "";
            this.txt_Ho.SelectionLength = 0;
            this.txt_Ho.SelectionStart = 0;
            this.txt_Ho.ShortcutsEnabled = true;
            this.txt_Ho.Size = new System.Drawing.Size(149, 43);
            this.txt_Ho.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Ho.TabIndex = 27;
            this.txt_Ho.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Ho.TextMarginBottom = 0;
            this.txt_Ho.TextMarginLeft = 3;
            this.txt_Ho.TextMarginTop = 1;
            this.txt_Ho.TextPlaceholder = "Enter text";
            this.txt_Ho.UseSystemPasswordChar = false;
            this.txt_Ho.WordWrap = true;
            // 
            // lbl_Luong1h
            // 
            this.lbl_Luong1h.AllowParentOverrides = false;
            this.lbl_Luong1h.AutoEllipsis = false;
            this.lbl_Luong1h.AutoSize = false;
            this.lbl_Luong1h.CursorType = null;
            this.lbl_Luong1h.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Luong1h.ForeColor = System.Drawing.Color.White;
            this.lbl_Luong1h.Location = new System.Drawing.Point(232, 797);
            this.lbl_Luong1h.Margin = new System.Windows.Forms.Padding(0);
            this.lbl_Luong1h.Name = "lbl_Luong1h";
            this.lbl_Luong1h.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.lbl_Luong1h.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_Luong1h.Size = new System.Drawing.Size(375, 30);
            this.lbl_Luong1h.TabIndex = 42;
            this.lbl_Luong1h.Text = "Lương 1 giờ";
            this.lbl_Luong1h.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_Luong1h.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txt_Ten
            // 
            this.txt_Ten.AcceptsReturn = false;
            this.txt_Ten.AcceptsTab = false;
            this.txt_Ten.AnimationSpeed = 200;
            this.txt_Ten.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Ten.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Ten.AutoSizeHeight = true;
            this.txt_Ten.BackColor = System.Drawing.Color.Transparent;
            this.txt_Ten.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Ten.BackgroundImage")));
            this.txt_Ten.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Ten.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Ten.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Ten.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Ten.BorderRadius = 1;
            this.txt_Ten.BorderThickness = 1;
            this.txt_Ten.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Ten.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Ten.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Ten.DefaultText = "";
            this.txt_Ten.FillColor = System.Drawing.Color.White;
            this.txt_Ten.ForeColor = System.Drawing.Color.Black;
            this.txt_Ten.HideSelection = true;
            this.txt_Ten.IconLeft = null;
            this.txt_Ten.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.IconPadding = 10;
            this.txt_Ten.IconRight = null;
            this.txt_Ten.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Ten.Lines = new string[0];
            this.txt_Ten.Location = new System.Drawing.Point(562, 158);
            this.txt_Ten.Margin = new System.Windows.Forms.Padding(0);
            this.txt_Ten.MaxLength = 32767;
            this.txt_Ten.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Ten.Modified = false;
            this.txt_Ten.Multiline = false;
            this.txt_Ten.Name = "txt_Ten";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Black;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Ten.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Ten.OnIdleState = stateProperties16;
            this.txt_Ten.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Ten.PasswordChar = '\0';
            this.txt_Ten.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Ten.PlaceholderText = "Enter text";
            this.txt_Ten.ReadOnly = false;
            this.txt_Ten.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Ten.SelectedText = "";
            this.txt_Ten.SelectionLength = 0;
            this.txt_Ten.SelectionStart = 0;
            this.txt_Ten.ShortcutsEnabled = true;
            this.txt_Ten.Size = new System.Drawing.Size(221, 43);
            this.txt_Ten.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Ten.TabIndex = 28;
            this.txt_Ten.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Ten.TextMarginBottom = 0;
            this.txt_Ten.TextMarginLeft = 3;
            this.txt_Ten.TextMarginTop = 1;
            this.txt_Ten.TextPlaceholder = "Enter text";
            this.txt_Ten.UseSystemPasswordChar = false;
            this.txt_Ten.WordWrap = true;
            // 
            // txt_Luong1h
            // 
            this.txt_Luong1h.AcceptsReturn = false;
            this.txt_Luong1h.AcceptsTab = false;
            this.txt_Luong1h.AnimationSpeed = 200;
            this.txt_Luong1h.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Luong1h.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Luong1h.AutoSizeHeight = true;
            this.txt_Luong1h.BackColor = System.Drawing.Color.Transparent;
            this.txt_Luong1h.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Luong1h.BackgroundImage")));
            this.txt_Luong1h.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Luong1h.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Luong1h.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Luong1h.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Luong1h.BorderRadius = 1;
            this.txt_Luong1h.BorderThickness = 1;
            this.txt_Luong1h.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Luong1h.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Luong1h.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong1h.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Luong1h.DefaultText = "";
            this.txt_Luong1h.FillColor = System.Drawing.Color.White;
            this.txt_Luong1h.ForeColor = System.Drawing.Color.Black;
            this.txt_Luong1h.HideSelection = true;
            this.txt_Luong1h.IconLeft = null;
            this.txt_Luong1h.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong1h.IconPadding = 10;
            this.txt_Luong1h.IconRight = null;
            this.txt_Luong1h.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong1h.Lines = new string[0];
            this.txt_Luong1h.Location = new System.Drawing.Point(222, 826);
            this.txt_Luong1h.MaxLength = 32767;
            this.txt_Luong1h.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Luong1h.Modified = false;
            this.txt_Luong1h.Multiline = false;
            this.txt_Luong1h.Name = "txt_Luong1h";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong1h.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Black;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Luong1h.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong1h.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong1h.OnIdleState = stateProperties20;
            this.txt_Luong1h.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Luong1h.PasswordChar = '\0';
            this.txt_Luong1h.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Luong1h.PlaceholderText = "Enter text";
            this.txt_Luong1h.ReadOnly = false;
            this.txt_Luong1h.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Luong1h.SelectedText = "";
            this.txt_Luong1h.SelectionLength = 0;
            this.txt_Luong1h.SelectionStart = 0;
            this.txt_Luong1h.ShortcutsEnabled = true;
            this.txt_Luong1h.Size = new System.Drawing.Size(385, 43);
            this.txt_Luong1h.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Luong1h.TabIndex = 41;
            this.txt_Luong1h.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Luong1h.TextMarginBottom = 0;
            this.txt_Luong1h.TextMarginLeft = 3;
            this.txt_Luong1h.TextMarginTop = 1;
            this.txt_Luong1h.TextPlaceholder = "Enter text";
            this.txt_Luong1h.UseSystemPasswordChar = false;
            this.txt_Luong1h.WordWrap = true;
            // 
            // txt_Sdt
            // 
            this.txt_Sdt.AcceptsReturn = false;
            this.txt_Sdt.AcceptsTab = false;
            this.txt_Sdt.AnimationSpeed = 200;
            this.txt_Sdt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Sdt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Sdt.AutoSizeHeight = true;
            this.txt_Sdt.BackColor = System.Drawing.Color.Transparent;
            this.txt_Sdt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Sdt.BackgroundImage")));
            this.txt_Sdt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Sdt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Sdt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Sdt.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Sdt.BorderRadius = 1;
            this.txt_Sdt.BorderThickness = 1;
            this.txt_Sdt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Sdt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Sdt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Sdt.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Sdt.DefaultText = "";
            this.txt_Sdt.FillColor = System.Drawing.Color.White;
            this.txt_Sdt.ForeColor = System.Drawing.Color.Black;
            this.txt_Sdt.HideSelection = true;
            this.txt_Sdt.IconLeft = null;
            this.txt_Sdt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Sdt.IconPadding = 10;
            this.txt_Sdt.IconRight = null;
            this.txt_Sdt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Sdt.Lines = new string[0];
            this.txt_Sdt.Location = new System.Drawing.Point(562, 322);
            this.txt_Sdt.Margin = new System.Windows.Forms.Padding(0);
            this.txt_Sdt.MaxLength = 32767;
            this.txt_Sdt.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Sdt.Modified = false;
            this.txt_Sdt.Multiline = false;
            this.txt_Sdt.Name = "txt_Sdt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Sdt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Black;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Sdt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Sdt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Sdt.OnIdleState = stateProperties24;
            this.txt_Sdt.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Sdt.PasswordChar = '\0';
            this.txt_Sdt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Sdt.PlaceholderText = "Enter text";
            this.txt_Sdt.ReadOnly = false;
            this.txt_Sdt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Sdt.SelectedText = "";
            this.txt_Sdt.SelectionLength = 0;
            this.txt_Sdt.SelectionStart = 0;
            this.txt_Sdt.ShortcutsEnabled = true;
            this.txt_Sdt.Size = new System.Drawing.Size(221, 43);
            this.txt_Sdt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Sdt.TabIndex = 29;
            this.txt_Sdt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Sdt.TextMarginBottom = 0;
            this.txt_Sdt.TextMarginLeft = 3;
            this.txt_Sdt.TextMarginTop = 1;
            this.txt_Sdt.TextPlaceholder = "Enter text";
            this.txt_Sdt.UseSystemPasswordChar = false;
            this.txt_Sdt.WordWrap = true;
            // 
            // txt_Email
            // 
            this.txt_Email.AcceptsReturn = false;
            this.txt_Email.AcceptsTab = false;
            this.txt_Email.AnimationSpeed = 200;
            this.txt_Email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Email.AutoSizeHeight = true;
            this.txt_Email.BackColor = System.Drawing.Color.Transparent;
            this.txt_Email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Email.BackgroundImage")));
            this.txt_Email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Email.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Email.BorderRadius = 1;
            this.txt_Email.BorderThickness = 1;
            this.txt_Email.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Email.DefaultText = "";
            this.txt_Email.FillColor = System.Drawing.Color.White;
            this.txt_Email.ForeColor = System.Drawing.Color.Black;
            this.txt_Email.HideSelection = true;
            this.txt_Email.IconLeft = null;
            this.txt_Email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Email.IconPadding = 10;
            this.txt_Email.IconRight = null;
            this.txt_Email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Email.Lines = new string[0];
            this.txt_Email.Location = new System.Drawing.Point(398, 592);
            this.txt_Email.Margin = new System.Windows.Forms.Padding(0);
            this.txt_Email.MaxLength = 32767;
            this.txt_Email.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Email.Modified = false;
            this.txt_Email.Multiline = false;
            this.txt_Email.Name = "txt_Email";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Email.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Black;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Email.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Email.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Email.OnIdleState = stateProperties28;
            this.txt_Email.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Email.PasswordChar = '\0';
            this.txt_Email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Email.PlaceholderText = "Enter text";
            this.txt_Email.ReadOnly = false;
            this.txt_Email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Email.SelectedText = "";
            this.txt_Email.SelectionLength = 0;
            this.txt_Email.SelectionStart = 0;
            this.txt_Email.ShortcutsEnabled = true;
            this.txt_Email.Size = new System.Drawing.Size(385, 43);
            this.txt_Email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Email.TabIndex = 39;
            this.txt_Email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Email.TextMarginBottom = 0;
            this.txt_Email.TextMarginLeft = 3;
            this.txt_Email.TextMarginTop = 1;
            this.txt_Email.TextPlaceholder = "Enter text";
            this.txt_Email.UseSystemPasswordChar = false;
            this.txt_Email.WordWrap = true;
            // 
            // txt_MaSoThue
            // 
            this.txt_MaSoThue.AcceptsReturn = false;
            this.txt_MaSoThue.AcceptsTab = false;
            this.txt_MaSoThue.AnimationSpeed = 200;
            this.txt_MaSoThue.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_MaSoThue.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_MaSoThue.AutoSizeHeight = true;
            this.txt_MaSoThue.BackColor = System.Drawing.Color.Transparent;
            this.txt_MaSoThue.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_MaSoThue.BackgroundImage")));
            this.txt_MaSoThue.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_MaSoThue.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_MaSoThue.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_MaSoThue.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_MaSoThue.BorderRadius = 1;
            this.txt_MaSoThue.BorderThickness = 1;
            this.txt_MaSoThue.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_MaSoThue.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_MaSoThue.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaSoThue.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_MaSoThue.DefaultText = "";
            this.txt_MaSoThue.FillColor = System.Drawing.Color.White;
            this.txt_MaSoThue.ForeColor = System.Drawing.Color.Black;
            this.txt_MaSoThue.HideSelection = true;
            this.txt_MaSoThue.IconLeft = null;
            this.txt_MaSoThue.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaSoThue.IconPadding = 10;
            this.txt_MaSoThue.IconRight = null;
            this.txt_MaSoThue.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_MaSoThue.Lines = new string[0];
            this.txt_MaSoThue.Location = new System.Drawing.Point(398, 502);
            this.txt_MaSoThue.Margin = new System.Windows.Forms.Padding(0);
            this.txt_MaSoThue.MaxLength = 32767;
            this.txt_MaSoThue.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_MaSoThue.Modified = false;
            this.txt_MaSoThue.Multiline = false;
            this.txt_MaSoThue.Name = "txt_MaSoThue";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaSoThue.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Black;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_MaSoThue.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaSoThue.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Black;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_MaSoThue.OnIdleState = stateProperties32;
            this.txt_MaSoThue.Padding = new System.Windows.Forms.Padding(3);
            this.txt_MaSoThue.PasswordChar = '\0';
            this.txt_MaSoThue.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_MaSoThue.PlaceholderText = "Enter text";
            this.txt_MaSoThue.ReadOnly = false;
            this.txt_MaSoThue.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_MaSoThue.SelectedText = "";
            this.txt_MaSoThue.SelectionLength = 0;
            this.txt_MaSoThue.SelectionStart = 0;
            this.txt_MaSoThue.ShortcutsEnabled = true;
            this.txt_MaSoThue.Size = new System.Drawing.Size(385, 43);
            this.txt_MaSoThue.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_MaSoThue.TabIndex = 37;
            this.txt_MaSoThue.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_MaSoThue.TextMarginBottom = 0;
            this.txt_MaSoThue.TextMarginLeft = 3;
            this.txt_MaSoThue.TextMarginTop = 1;
            this.txt_MaSoThue.TextPlaceholder = "Enter text";
            this.txt_MaSoThue.UseSystemPasswordChar = false;
            this.txt_MaSoThue.WordWrap = true;
            // 
            // txt_CCCD
            // 
            this.txt_CCCD.AcceptsReturn = false;
            this.txt_CCCD.AcceptsTab = false;
            this.txt_CCCD.AnimationSpeed = 200;
            this.txt_CCCD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_CCCD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_CCCD.AutoSizeHeight = true;
            this.txt_CCCD.BackColor = System.Drawing.Color.Transparent;
            this.txt_CCCD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_CCCD.BackgroundImage")));
            this.txt_CCCD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_CCCD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_CCCD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_CCCD.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_CCCD.BorderRadius = 1;
            this.txt_CCCD.BorderThickness = 1;
            this.txt_CCCD.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_CCCD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_CCCD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_CCCD.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_CCCD.DefaultText = "";
            this.txt_CCCD.FillColor = System.Drawing.Color.White;
            this.txt_CCCD.ForeColor = System.Drawing.Color.Black;
            this.txt_CCCD.HideSelection = true;
            this.txt_CCCD.IconLeft = null;
            this.txt_CCCD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_CCCD.IconPadding = 10;
            this.txt_CCCD.IconRight = null;
            this.txt_CCCD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_CCCD.Lines = new string[0];
            this.txt_CCCD.Location = new System.Drawing.Point(398, 411);
            this.txt_CCCD.Margin = new System.Windows.Forms.Padding(0);
            this.txt_CCCD.MaxLength = 32767;
            this.txt_CCCD.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_CCCD.Modified = false;
            this.txt_CCCD.Multiline = false;
            this.txt_CCCD.Name = "txt_CCCD";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_CCCD.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Black;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_CCCD.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_CCCD.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Black;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_CCCD.OnIdleState = stateProperties36;
            this.txt_CCCD.Padding = new System.Windows.Forms.Padding(3);
            this.txt_CCCD.PasswordChar = '\0';
            this.txt_CCCD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_CCCD.PlaceholderText = "Enter text";
            this.txt_CCCD.ReadOnly = false;
            this.txt_CCCD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_CCCD.SelectedText = "";
            this.txt_CCCD.SelectionLength = 0;
            this.txt_CCCD.SelectionStart = 0;
            this.txt_CCCD.ShortcutsEnabled = true;
            this.txt_CCCD.Size = new System.Drawing.Size(385, 43);
            this.txt_CCCD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_CCCD.TabIndex = 35;
            this.txt_CCCD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_CCCD.TextMarginBottom = 0;
            this.txt_CCCD.TextMarginLeft = 3;
            this.txt_CCCD.TextMarginTop = 1;
            this.txt_CCCD.TextPlaceholder = "Enter text";
            this.txt_CCCD.UseSystemPasswordChar = false;
            this.txt_CCCD.WordWrap = true;
            // 
            // btn_save
            // 
            this.btn_save.AllowAnimations = true;
            this.btn_save.AllowMouseEffects = true;
            this.btn_save.AllowToggling = false;
            this.btn_save.AnimationSpeed = 200;
            this.btn_save.AutoGenerateColors = false;
            this.btn_save.AutoRoundBorders = false;
            this.btn_save.AutoSizeLeftIcon = true;
            this.btn_save.AutoSizeRightIcon = true;
            this.btn_save.BackColor = System.Drawing.Color.Transparent;
            this.btn_save.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_save.BackgroundImage")));
            this.btn_save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.ButtonText = "Save";
            this.btn_save.ButtonTextMarginLeft = 0;
            this.btn_save.ColorContrastOnClick = 45;
            this.btn_save.ColorContrastOnHover = 45;
            this.btn_save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_save.CustomizableEdges = borderEdges1;
            this.btn_save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_save.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_save.ForeColor = System.Drawing.Color.White;
            this.btn_save.IconLeft = null;
            this.btn_save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_save.IconMarginLeft = 11;
            this.btn_save.IconPadding = 10;
            this.btn_save.IconRight = null;
            this.btn_save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_save.IconSize = 25;
            this.btn_save.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_save.IdleBorderRadius = 0;
            this.btn_save.IdleBorderThickness = 0;
            this.btn_save.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_save.IdleIconLeftImage = null;
            this.btn_save.IdleIconRightImage = null;
            this.btn_save.IndicateFocus = false;
            this.btn_save.Location = new System.Drawing.Point(109, 524);
            this.btn_save.Name = "btn_save";
            this.btn_save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.OnDisabledState.BorderRadius = 1;
            this.btn_save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnDisabledState.BorderThickness = 1;
            this.btn_save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_save.OnDisabledState.IconLeftImage = null;
            this.btn_save.OnDisabledState.IconRightImage = null;
            this.btn_save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.BorderRadius = 1;
            this.btn_save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.onHoverState.BorderThickness = 1;
            this.btn_save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_save.onHoverState.IconLeftImage = null;
            this.btn_save.onHoverState.IconRightImage = null;
            this.btn_save.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.OnIdleState.BorderRadius = 1;
            this.btn_save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnIdleState.BorderThickness = 1;
            this.btn_save.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnIdleState.IconLeftImage = null;
            this.btn_save.OnIdleState.IconRightImage = null;
            this.btn_save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.BorderRadius = 1;
            this.btn_save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_save.OnPressedState.BorderThickness = 1;
            this.btn_save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnPressedState.IconLeftImage = null;
            this.btn_save.OnPressedState.IconRightImage = null;
            this.btn_save.Size = new System.Drawing.Size(150, 39);
            this.btn_save.TabIndex = 48;
            this.btn_save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_save.TextMarginLeft = 0;
            this.btn_save.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_save.UseDefaultRadiusAndThickness = true;
            this.btn_save.Click += new System.EventHandler(this.btn_save_Click);
            // 
            // txt_Luong
            // 
            this.txt_Luong.AcceptsReturn = false;
            this.txt_Luong.AcceptsTab = false;
            this.txt_Luong.AnimationSpeed = 200;
            this.txt_Luong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Luong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Luong.AutoSizeHeight = true;
            this.txt_Luong.BackColor = System.Drawing.Color.Transparent;
            this.txt_Luong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Luong.BackgroundImage")));
            this.txt_Luong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Luong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Luong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Luong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_Luong.BorderRadius = 1;
            this.txt_Luong.BorderThickness = 1;
            this.txt_Luong.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txt_Luong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Luong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_Luong.DefaultText = "";
            this.txt_Luong.FillColor = System.Drawing.Color.White;
            this.txt_Luong.ForeColor = System.Drawing.Color.Black;
            this.txt_Luong.HideSelection = true;
            this.txt_Luong.IconLeft = null;
            this.txt_Luong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong.IconPadding = 10;
            this.txt_Luong.IconRight = null;
            this.txt_Luong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Luong.Lines = new string[0];
            this.txt_Luong.Location = new System.Drawing.Point(398, 690);
            this.txt_Luong.Margin = new System.Windows.Forms.Padding(0);
            this.txt_Luong.MaxLength = 32767;
            this.txt_Luong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Luong.Modified = false;
            this.txt_Luong.Multiline = false;
            this.txt_Luong.Name = "txt_Luong";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Black;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Luong.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Black;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Luong.OnIdleState = stateProperties40;
            this.txt_Luong.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Luong.PasswordChar = '\0';
            this.txt_Luong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Luong.PlaceholderText = "Enter text";
            this.txt_Luong.ReadOnly = false;
            this.txt_Luong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Luong.SelectedText = "";
            this.txt_Luong.SelectionLength = 0;
            this.txt_Luong.SelectionStart = 0;
            this.txt_Luong.ShortcutsEnabled = true;
            this.txt_Luong.Size = new System.Drawing.Size(385, 43);
            this.txt_Luong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Luong.TabIndex = 49;
            this.txt_Luong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Luong.TextMarginBottom = 0;
            this.txt_Luong.TextMarginLeft = 3;
            this.txt_Luong.TextMarginTop = 1;
            this.txt_Luong.TextPlaceholder = "Enter text";
            this.txt_Luong.UseSystemPasswordChar = false;
            this.txt_Luong.WordWrap = true;
            // 
            // lbl_Ho
            // 
            this.lbl_Ho.AutoSize = true;
            this.lbl_Ho.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Ho.Location = new System.Drawing.Point(404, 128);
            this.lbl_Ho.Name = "lbl_Ho";
            this.lbl_Ho.Size = new System.Drawing.Size(31, 20);
            this.lbl_Ho.TabIndex = 51;
            this.lbl_Ho.Text = "Họ";
            // 
            // lbl_Ten
            // 
            this.lbl_Ten.AutoSize = true;
            this.lbl_Ten.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Ten.Location = new System.Drawing.Point(558, 128);
            this.lbl_Ten.Name = "lbl_Ten";
            this.lbl_Ten.Size = new System.Drawing.Size(36, 20);
            this.lbl_Ten.TabIndex = 52;
            this.lbl_Ten.Text = "Tên";
            // 
            // lbl_GioiTinh
            // 
            this.lbl_GioiTinh.AutoSize = true;
            this.lbl_GioiTinh.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_GioiTinh.Location = new System.Drawing.Point(404, 213);
            this.lbl_GioiTinh.Name = "lbl_GioiTinh";
            this.lbl_GioiTinh.Size = new System.Drawing.Size(73, 20);
            this.lbl_GioiTinh.TabIndex = 53;
            this.lbl_GioiTinh.Text = "Giới tính";
            // 
            // lbl_NgaySinh
            // 
            this.lbl_NgaySinh.AutoSize = true;
            this.lbl_NgaySinh.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_NgaySinh.Location = new System.Drawing.Point(558, 213);
            this.lbl_NgaySinh.Name = "lbl_NgaySinh";
            this.lbl_NgaySinh.Size = new System.Drawing.Size(82, 20);
            this.lbl_NgaySinh.TabIndex = 54;
            this.lbl_NgaySinh.Text = "Ngày sinh";
            // 
            // lbl_ChucVu
            // 
            this.lbl_ChucVu.AutoSize = true;
            this.lbl_ChucVu.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_ChucVu.Location = new System.Drawing.Point(404, 294);
            this.lbl_ChucVu.Name = "lbl_ChucVu";
            this.lbl_ChucVu.Size = new System.Drawing.Size(67, 20);
            this.lbl_ChucVu.TabIndex = 55;
            this.lbl_ChucVu.Text = "Chức vụ";
            // 
            // lbl_Sdt
            // 
            this.lbl_Sdt.AutoSize = true;
            this.lbl_Sdt.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Sdt.Location = new System.Drawing.Point(558, 294);
            this.lbl_Sdt.Name = "lbl_Sdt";
            this.lbl_Sdt.Size = new System.Drawing.Size(106, 20);
            this.lbl_Sdt.TabIndex = 56;
            this.lbl_Sdt.Text = "Số điện thoại";
            // 
            // lbl_CCCD
            // 
            this.lbl_CCCD.AutoSize = true;
            this.lbl_CCCD.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_CCCD.Location = new System.Drawing.Point(404, 381);
            this.lbl_CCCD.Name = "lbl_CCCD";
            this.lbl_CCCD.Size = new System.Drawing.Size(145, 20);
            this.lbl_CCCD.TabIndex = 57;
            this.lbl_CCCD.Text = "Căn cước công dân";
            // 
            // lbl_MaSoThue
            // 
            this.lbl_MaSoThue.AutoSize = true;
            this.lbl_MaSoThue.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_MaSoThue.Location = new System.Drawing.Point(404, 473);
            this.lbl_MaSoThue.Name = "lbl_MaSoThue";
            this.lbl_MaSoThue.Size = new System.Drawing.Size(89, 20);
            this.lbl_MaSoThue.TabIndex = 58;
            this.lbl_MaSoThue.Text = "Mã số thuế";
            // 
            // lbl_Email
            // 
            this.lbl_Email.AutoSize = true;
            this.lbl_Email.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Email.Location = new System.Drawing.Point(404, 562);
            this.lbl_Email.Name = "lbl_Email";
            this.lbl_Email.Size = new System.Drawing.Size(49, 20);
            this.lbl_Email.TabIndex = 59;
            this.lbl_Email.Text = "Email";
            // 
            // lbl_Luong
            // 
            this.lbl_Luong.AutoSize = true;
            this.lbl_Luong.Font = new System.Drawing.Font("Segoe UI Black", 9F, System.Drawing.FontStyle.Bold);
            this.lbl_Luong.Location = new System.Drawing.Point(404, 660);
            this.lbl_Luong.Name = "lbl_Luong";
            this.lbl_Luong.Size = new System.Drawing.Size(97, 20);
            this.lbl_Luong.TabIndex = 60;
            this.lbl_Luong.Text = "Lương 1 giờ";
            // 
            // F_NhanVienCRUD
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(829, 784);
            this.Controls.Add(this.lbl_Luong);
            this.Controls.Add(this.lbl_Email);
            this.Controls.Add(this.lbl_MaSoThue);
            this.Controls.Add(this.lbl_CCCD);
            this.Controls.Add(this.lbl_Sdt);
            this.Controls.Add(this.lbl_ChucVu);
            this.Controls.Add(this.lbl_NgaySinh);
            this.Controls.Add(this.lbl_GioiTinh);
            this.Controls.Add(this.lbl_Ten);
            this.Controls.Add(this.lbl_Ho);
            this.Controls.Add(this.txt_Luong);
            this.Controls.Add(this.btn_save);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.txt_GioiTinh);
            this.Controls.Add(this.txt_ChucVu);
            this.Controls.Add(this.txt_Ho);
            this.Controls.Add(this.lbl_Luong1h);
            this.Controls.Add(this.txt_Ten);
            this.Controls.Add(this.txt_Luong1h);
            this.Controls.Add(this.txt_Sdt);
            this.Controls.Add(this.txt_Email);
            this.Controls.Add(this.txt_MaSoThue);
            this.Controls.Add(this.txt_CCCD);
            this.Controls.Add(this.pb_image);
            this.Name = "F_NhanVienCRUD";
            this.Text = "F_NhanVienCRUD";
            ((System.ComponentModel.ISupportInitialize)(this.pb_image)).EndInit();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPictureBox pb_image;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuDatePicker bDP_NgaySinh;
        private Bunifu.UI.WinForms.BunifuTextBox txt_GioiTinh;
        private Bunifu.UI.WinForms.BunifuTextBox txt_ChucVu;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Ho;
        private Bunifu.UI.WinForms.BunifuLabel lbl_Luong1h;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Ten;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Luong1h;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Sdt;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Email;
        private Bunifu.UI.WinForms.BunifuTextBox txt_MaSoThue;
        private Bunifu.UI.WinForms.BunifuTextBox txt_CCCD;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_save;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Luong;
        private System.Windows.Forms.Label lbl_Ho;
        private System.Windows.Forms.Label lbl_Ten;
        private System.Windows.Forms.Label lbl_GioiTinh;
        private System.Windows.Forms.Label lbl_NgaySinh;
        private System.Windows.Forms.Label lbl_ChucVu;
        private System.Windows.Forms.Label lbl_Sdt;
        private System.Windows.Forms.Label lbl_CCCD;
        private System.Windows.Forms.Label lbl_MaSoThue;
        private System.Windows.Forms.Label lbl_Email;
        private System.Windows.Forms.Label lbl_Luong;
    }
}